---
name: ci

on:
  pull_request:
    paths:
      - '**.ya?ml'
  push:
    branches:
      - main
    paths:
      - '**.ya?ml'

jobs:
  workflow-ci:
    uses: vergesense/gha-workflow-ci/.github/workflows/workflow_ci.yml@v1
