---
name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # check-workflow-version:
  #   uses: vergesense/gha-check-workflow-versions/.github/workflows/check_workflow_versions.yml@4c302b7a5dd330981cd1b3d26c95b95ca05d9ce8
  #   with:
  #     repo-name: 'gha-workflow-ci'
  #     reusable-workflow-job-id: workflow-ci
  #     gha-workflow-file-name: ci.yml
  #   secrets:
  #     github-access-token: ${{ secrets.DEVOPS_GITHUB_MACHINE_PAT }}
  workflow-ci:
    uses: vergesense/gha-workflow-ci/.github/workflows/workflow_ci.yml@v1
