---
name: workflow_ci

on:
  workflow_call:
    inputs:
      actionlint-ignore:
        description: Add an ignore statement to the actionlint command
        required: false
        type: string

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install yamllint==1.26.3
      - run: yamllint .
  actionlint:
    runs-on: ubuntu-latest
    container:
      image: rhysd/actionlint:1.6.12
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: run-actionlint
        run: |
          mkdir .git
          actionlint -color ${{ inputs.actionlint-ignore }}
